# Pull base image to build with
FROM alpine:3.9 as build

COPY ./requirements /tmp/requirements
WORKDIR /tmp/requirements

RUN echo "Install dev packages"                                 && \
    apk add --no-cache build-base libffi-dev==3.2.1-r6  \
    openssl-dev==1.1.1g-r0 python3-dev==3.6.9-r2  \
    ca-certificates==20191127-r0

RUN echo "Upgrade pip and setuptools"                           && \
    python3 -m pip install --upgrade -r requirements-build.txt

RUN echo "Compile Ansible and linting tools"                    && \
    python3 -m pip wheel --wheel-dir=/root/wheels -r  \
    requirements-ansible.txt

RUN echo "Compile static analysis tools"                        && \
    python3 -m pip wheel --wheel-dir=/root/wheels -r  \
    requirements-lint.txt



# Production image
FROM python:3.6-alpine

LABEL maintainer="amfortesramos@hotmail.com"
LABEL version="1.0"
LABEL description="Ansible-Networking Docker Image"
LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/local/bin/node"

# Copy the artifacts over. Keeps the prod image small.
COPY --from=build /root/wheels /root/wheels

RUN echo "Install compiled Python packages"                     && \
    python3 -m pip install /root/wheels/*

RUN apk add --no-cache --virtual .pipeline-deps  \
    readline==8.0.1-r0  linux-pam==1.3.1-r1                     && \
    apk add --no-cache nodejs==12.15.0-r1 bash==5.0.11-r1  \
    sudo==1.8.31-r0 shadow==4.7-r1                              && \
    apk del .pipeline-deps

# Default command: display Ansible version
CMD [ "ansible", "--version" ]
